CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(64) NOT NULL,
    avatar_url VARCHAR(512),
    phone_ciphertext VARBINARY(512),
    phone_hash CHAR(64),
    status VARCHAR(32) NOT NULL,
    privacy_mode BOOLEAN NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE user_auths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_uid VARCHAR(128) NOT NULL,
    credential_hash VARCHAR(255),
    verified BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_user_auth_provider_uid UNIQUE (provider, provider_uid)
);

CREATE TABLE user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    refresh_token_hash CHAR(64) NOT NULL UNIQUE,
    device_id VARCHAR(128),
    device_name VARCHAR(128),
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL,
    currency CHAR(3) NOT NULL,
    is_default BOOLEAN NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ledger_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL,
    balance DECIMAL(19, 2) NOT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL,
    balance_updated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    parent_id BIGINT,
    type VARCHAR(16) NOT NULL,
    code VARCHAR(64),
    name VARCHAR(64) NOT NULL,
    icon VARCHAR(64),
    color CHAR(7),
    is_system BOOLEAN NOT NULL,
    status VARCHAR(32) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT uq_categories_type_code UNIQUE (type, code)
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ledger_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    target_account_id BIGINT,
    category_id BIGINT,
    request_id VARCHAR(64),
    type VARCHAR(16) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    balance_delta DECIMAL(19, 2),
    occurred_at TIMESTAMP NOT NULL,
    note VARCHAR(500),
    source VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    is_system BOOLEAN NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT uq_transactions_user_request UNIQUE (user_id, request_id)
);

CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ledger_id BIGINT NOT NULL,
    budget_month DATE NOT NULL,
    category_id BIGINT,
    amount DECIMAL(19, 2) NOT NULL,
    alert_threshold DECIMAL(5, 2) NOT NULL,
    enabled BOOLEAN NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

INSERT INTO categories (
    user_id, parent_id, type, code, name, icon, color,
    is_system, status, sort_order, created_at, updated_at, deleted_at
) VALUES
    (NULL, NULL, 'EXPENSE', 'FOOD', '餐饮', 'utensils', '#D6FF24', TRUE, 'ACTIVE', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (NULL, NULL, 'INCOME', 'SALARY', '工资', 'wallet-cards', '#4EF28A', TRUE, 'ACTIVE', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
